### ISSUE TITLE
add comment tracking to examples

### ISSUE THREAD

**Issue by mdahlhausen** [HydraShare/hydra#18]
@mostaphaRoudsari do you think we should add comments to each of the examples? It'll be easy to add a [Disqus](https://disqus.com/home/) comment chain to each example.

**Comment by mostaphaRoudsari** [comment]
Hi @mdahlhausen. It's not clear to me how to add it to the page but that would be a huge move forward. How does it work? Are they going to take care of keeping the comments? Will it be different for each page address? I'm asking since Hydra is a single page application. Can we have different discussion/commenting for the same page with different hashes?
I'm going to modify the code to use pushState or location.hash for different users. That might also help for this purpose.

**Comment by mdahlhausen** [comment]
@mostaphaRoudsari .  I'll test it out offline before I push it live, but [disqus](https://disqus.com/) handles comments by the unique url, so I think we'll be fine.  I'll work on it later this week.

**Comment by mostaphaRoudsari** [comment]
Nice! I'm working on #2 and #15.

**Comment by mdahlhausen** [comment]
Added comments with [this commit](https://github.com/HydraShare/hydra/commit/149081484d05b497cf7fe9873a9b37da324f2a44).  There is a separate comment thread for each example.

**Comment by mostaphaRoudsari** [comment]
@mdahlhausen this is so sweet! Next step will be to write the script to keep track of number of downloads and comments. I can't do it this weekend and next one - working on release and will have a workshop- but then the week after that I will do it.

**Comment by mdahlhausen** [comment]
@mostaphaRoudsari disqus has [a post](https://help.disqus.com/customer/portal/articles/565624) on adding comment counts to a webpage.

**Comment by mostaphaRoudsari** [comment]
Thanks @mdahlhausen! I added a new issue so I don't forget it. #26
