### ISSUE TITLE
Updating structure of README.md

### ISSUE THREAD

**Issue by mostaphaRoudsari** [HydraShare/hydra#5]
@chriswmackey here are some thought about REASME.md

First of all I think we can merge README.md and changelog.MD into a single file > README.md and use mark down to separate them.

We can/should also add tags and dependencies inside README.md. It will make it google searchable and human-readable on the github page.

One more enhancement is to add a link at the end of the README.me to visualize it on Hydra. To generate the link you will need user's github account that can be an input for the component then it will look like:

http://hydrashare.github.io/hydra/viewer?owner=*githuboccountname&description=*projectname

For example:
http://hydrashare.github.io/hydra/viewer?owner=ayezioro&description=Bounce_Out

[Check this example on Hydra](http://hydrashare.github.io/hydra/viewer?owner=ayezioro&description=Bounce_Out)

Finally if we can add a link to thumbnail image so it will be rendered once you open the github page it would be very helpful. We will also need the user account name in github to include the link inside the file.

The file would look like

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I have implemented all that you have requested with a few minor edits:
https://github.com/HydraShare/hydra/commit/326a01c68ba02f9d4f01a39a8573eeed84abcc72

Instead of writing "Changelog" I have just written the version of the component and then any change log text below it.  This will make it not look weird if someone is committing a file for the first time or does not want to include a changelog.  I also put in some functions to parse and read any old README (if it exists) such that the change log will be a running list of all versions of the file that a user has uploaded.

Also, there is no need to require the user to input their github username to the component since I can find out what their username is through the config file in the .git folder of their fork on their computer.  Generally, I want to try to make as few required inputs as possible since I could tell that this was a big barrier to entry for new people just trying out the component.

Along the line of the user's account name, I also put in a link to the user's account in the README so that people can go from the hydra page to the user's page if they want to access all of the example files that someone has uploaded (if you have any easy way of generating this page, I think that a lot of people will want quick access to it).

Let me know if I am forgetting anything and, if not, close out the issue!

-Chris

**Comment by chriswmackey** [comment]
I had to fix a few bugs:
https://github.com/HydraShare/hydra/commit/670fae0b5fefbc7b62e088fca83201393a5f1d60

Here's a page showing the new format:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&description=Outdoor_Comfort_Shade_Benefit

**Comment by chriswmackey** [comment]
One final commit that gets the thumbnail working correctly:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&description=Psychrometric_Chart

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks! I had to make a couple of changes that will break your links. I replaced "description" with "id" and added "fork" to address #7. Here is an example:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra&id=Psychrometric_Chart

Let me know if you want me to update the Grasshopper component.

**Comment by chriswmackey** [comment]
Also, I have to stop the changelog from being a running list

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

This issue has now been addressed:
https://github.com/HydraShare/hydra/commit/68e2cacf9449c905d51acd931b1fb0d3c4ec8e39

You can see the new readme in action here:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Outdoor_Comfort_Shade_Benefit

Everything should now be solid with the ReadMe and so I am closing out the issue.  If I made a mistake, feel free to re-open.

-Chris
