### ISSUE TITLE
Various browsers issues

### ISSUE THREAD

**Issue by ayezioro** [HydraShare/hydra#9]
I'm having some browser issues (Firefox, Chrome and MS Edge) with some of the u[ploaded files: Armature for Maximum Solar, Armature for Energy-Positive Building Experiment and XmasQMEF. The image crashes the page. The worst is in Firefox, where the browser turns black (all of it).
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

Your Armature for Energy-Positive Building Experiment is displaying fine in my firefox:
![gh ok](https://cloud.githubusercontent.com/assets/5567574/10181006/c6dd0b40-66e0-11e5-88a2-fc8b07ba095f.JPG)

I imagine that your issue is related to the fact that all of those example files have the maximum size possible for the high-res image of the GH canvas.  I might have to drop this size down if we are not able to fix it on your system.

What type of speed do you have for your internet?
http://ma.speedtest.rcn.net/

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
I'm at home right now. The test speed  for download is 10.5 Mbps, which is slow from what i expect (30). But i tried this also at my university which gas a pretty much fast connection.
I was thinking that a restart will do, but right now this happened again (black window in firefox).
MS Edge doesn't show the image but a computer screen with a X on it.
The example remaining is the one of your screenshot.
... don't know what to say ...
Thanks,
-A.
P.S. Now in the university. Speed download: 63 Mbps (also low than what i expected but good).

**Comment by chriswmackey** [comment]
@ayezioro ,
I will admit that I have also had some issues sometimes when I try to load a GH script with a large detailed image.  Refreshing my browser a few times usually gets it to work.  My guess is that this is what is happening in your firefox and I may have to reduce the max image size.
Can you confirm whether you are able to see small images of the canvas as well? Such as this one?
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&description=Color_Library

If so, Let's try to find the maximum image size before your browser fails and I will set the max image size to that.
My guess with MS edge is that Microsoft is trying to be the usual bully it has historically been in the web development space and they don't support open libraries that the rest of us want to use since they want us to use their proprietary terrible stuff.  I am inclined to forget about them.

-Chris

**Comment by ayezioro** [comment]
Hi CHris,
I can see well the link you sent.
I kind of like the MS Edge, though is not my default browser (firefox is).
Chrome is also not happy with some of the links.
See the image:
On the left is what i get in Edge, on the right with Chrome. Firefox is just a black window that i can't even refresh. Everything is disabled.
![capture](https://cloud.githubusercontent.com/assets/7526023/10201149/33fe15de-67b3-11e5-8d71-bc3630386626.JPG)

Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
I think the example is removed. I close the issue for now until we find a new example that has this issue
